spring:
  application:
    name: spring-config-server
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suraj21090/spring-config-server
          search-paths: service-config/
server:
  port: 8666
management:
  security:
    enabled: false
